"""empty message

Revision ID: 3e91e0fe48a6
Revises: 7ddeb00088c3
Create Date: 2021-05-23 01:19:08.304572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e91e0fe48a6'
down_revision = '7ddeb00088c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('suffix', sa.Text(), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_actor_first_name'), ['first_name', 'middle_name', 'last_name', 'suffix'])

    with op.batch_alter_table('author', schema=None) as batch_op:
        batch_op.add_column(sa.Column('suffix', sa.Text(), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_author_first_name'), ['first_name', 'middle_name', 'last_name', 'suffix'])

    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_book_universe_id'), ['universe_id', 'series_id', 'title'])

    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('suffix', sa.Text(), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_character_series_id'), ['series_id', 'first_name', 'last_name', 'suffix', 'parent_id'])

    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_series_title'), ['title'])

    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_tag_name'), ['name', 'tag_type_id'])

    with op.batch_alter_table('tag_type', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_tag_type_name'), ['name'])

    with op.batch_alter_table('universe', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_universe_title'), ['title'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('universe', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_universe_title'), type_='unique')

    with op.batch_alter_table('tag_type', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_tag_type_name'), type_='unique')

    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_tag_name'), type_='unique')

    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_series_title'), type_='unique')

    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_character_series_id'), type_='unique')
        batch_op.drop_column('suffix')

    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_book_universe_id'), type_='unique')

    with op.batch_alter_table('author', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_author_first_name'), type_='unique')
        batch_op.drop_column('suffix')

    with op.batch_alter_table('actor', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_actor_first_name'), type_='unique')
        batch_op.drop_column('suffix')

    # ### end Alembic commands ###
