"""empty message

Revision ID: 4746389be9e5
Revises: 04e1412c3058
Create Date: 2021-05-26 16:51:27.075956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4746389be9e5'
down_revision = '04e1412c3058'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actor', schema=None) as batch_op:
        batch_op.alter_column('first_name',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('last_name',
               existing_type=sa.TEXT(),
               nullable=False)

    with op.batch_alter_table('author', schema=None) as batch_op:
        batch_op.alter_column('first_name',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('last_name',
               existing_type=sa.TEXT(),
               nullable=False)

    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.alter_column('first_name',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('last_name',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.alter_column('last_name',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('first_name',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('author', schema=None) as batch_op:
        batch_op.alter_column('last_name',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('first_name',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('actor', schema=None) as batch_op:
        batch_op.alter_column('last_name',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('first_name',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###
