"""empty message

Revision ID: 86215255d698
Revises: 3e91e0fe48a6
Create Date: 2021-05-25 23:23:45.235784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86215255d698'
down_revision = '3e91e0fe48a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('art', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_art_title'), ['title', 'source'])

    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_constraint('uq_character_series_id', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_character_series_id'), ['series_id', 'first_name', 'last_name', 'suffix'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_character_series_id'), type_='unique')
        batch_op.create_unique_constraint('uq_character_series_id', ['series_id', 'first_name', 'last_name', 'suffix', 'parent_id'])

    with op.batch_alter_table('art', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_art_title'), type_='unique')

    # ### end Alembic commands ###
